# Reusable GitHub Actions workflow to run Playwright site-up test
# Save as .github/workflows/playwright-site-up.yml

name: Playwright Site Up Test

on:
  workflow_call:
    inputs:
      url:
        description: 'The URL of the site to test'
        required: true
        type: string

jobs:
  playwright-site-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest playwright
          playwright install chromium

      - name: Run Playwright site-up test
        run: |
          pytest --base-url="${{ inputs.url }}" test/playwright_site_up.py
