name: Playwright Smoke Test After Deploy

on:
  workflow_run:
    workflows: ["Azure Static Web Apps CI/CD"]
    types:
      - completed

jobs:
  call-playwright-smoke:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/playwright-smoke.yml
    with:
      site-url: ${{ vars.AZURE_SITE_URL }}