name: Playwright Smoke Tests

on:
  workflow_call:
    inputs:
      site-url:
        description: 'The URL of the site to test'
        required: true
        type: string

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest
          playwright install

      - name: Run Playwright smoke tests
        run: |
          python tests/test_smoke.py ${{ inputs.site-url }}
